# Customization of the appearance of the item.
items:
  invisible_item_frame:
    # What the name of the item should be.
    name: §rInvisible Item Frame

    # Uncomment to assign lore text for the item.
    #lore:
    #  - line1
    #  - line2

  invisible_glow_item_frame:
    name: §rInvisible Glow Item Frame

# Customization for the crafting recipe.
recipes:
  invisible_item_frame:
    # Whether the recipe should be usable.
    enabled: true

    # Items that are required for crafting.
    ingredients:
      - minecraft:item_frame
      - minecraft:glass_pane

    # How many of the item should be produced by the recipe.
    count: 1

  invisible_glow_item_frame:
    enabled: true

    ingredients:
      - minecraft:glow_item_frame
      - minecraft:glass_pane

    count: 1
